server:
  port: 8083
dubbo:
  application:
    name: dubbo-consumer
  registry:     #注册中心配置，用于配置连接注册中心相关信息
    address: zookeeper://47.101.197.120:2181
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
    name: dubbo
    port: 20884
